spring.application.name=Fitness-Monolith

server.port=${PORT:8080}

# MYSQL
#spring.datasource.url=jdbc:mysql://localhost:3306/fitness_tracker_monolithic
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connecting to Neon DB, Hosted Postgres Database
# postgresql://neondb_owner:npg_vDo1nOUfW8Sm@ep-super-pine-ajmg51c8-pooler.c-3.us-east-2.aws.neon.tech/fitness_tracker_monolithic?sslmode=require&channel_binding=require


# Externalize for Docker
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Create Jar Using Powershell, For that set dynamic variable like this below
# $env:DB_URL="jdbc:mysql://localhost:3306/fitness_tracker_monolithic"
# $env:DB_USERNAME="root"
# $env:DB_PASSWORD="root"
# ./mnvw package

# Create Docker Image Like this
# ./mvnw spring-boot:build-image
# If you have Dockerfile then
# docker build -t fitness-monolith .

# Run docker image
# docker run -p 8080:8080
# -e DB_URL=jdbc:mysql://host.docker.internal:3306/fitness_tracker_monolithic
# -e DB_USERNAME=root
# -e DB_PASSWORD=root fitness-monolith:0.0.1-SNAPSHOT

# Push Image to Docker Hub
# docker tag fitness-monolith naruto720/fitness-monolith
# docker login
# docker push naruto720/fitness-monolith


#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt-secret=xjgnNP/MGwkVllA/fR+NGRZtrQQnyyRh0aMfR40womZNA6ovrdnG4uQor9uYBfvX
app.jwt-expiration=86400000